// URETILEN DOSYA. Elle duzenleme: kaynak tray\lang\tray-<lang>.json,
// uretec tray\gen-strings.js.

static partial class L
{
    static partial void BuildRest()
    {
        Add("ar", new string[] {
            "alreadyRunning", "surecut-deck قيد التشغيل بالفعل.",
            "running", "● قيد التشغيل  ·  المنفذ ",
            "stopped", "○ متوقف",
            "pairCode", "رمز الاقتران:  ",
            "openEditor", "فتح المحرر",
            "dragDrop", "سحب وإفلات اختصار…",
            "serverInfo", "تفاصيل الخادم…",
            "openInBrowser", "فتح الواجهة في المتصفح",
            "copyAddress", "نسخ عنوان الاتصال",
            "settings", "الإعدادات…",
            "log", "السجل…",
            "restart", "إعادة التشغيل",
            "stop", "إيقاف",
            "start", "تشغيل",
            "quit", "إنهاء",
            "nodeFailed", "تعذّر تشغيل Node.js:\\n\\n",
            "nodeFailedHint", "\\n\\nيجب أن يكون Node.js مثبتًا ومتاحًا في PATH.",
            "trayRunning", "surecut-deck: قيد التشغيل (المنفذ ",
            "trayStopped", "surecut-deck: متوقف",
            "notGenerated", "(لم يُنشأ بعد)",
            "editorFellBack", "تعذّر فتح نافذة المحرر، سيتم استخدام المتصفح. التفاصيل: السجل",
            "copied", "تم النسخ: ",
            "newCode", "رمز اقتران جديد: ",
            "newCodeHint", "\\n\\nسيُفصل الجهاز اللوحي وسيحتاج إلى الرمز الجديد.",
            "autoStartFailed", "تعذّر إعداد التشغيل التلقائي: ",
            "dropTitle", "surecut-deck: سحب وإفلات",
            "dropZone", "اسحب اختصارًا من سطح المكتب\\r\\nوأفلته هنا\\r\\n\\r\\n(برنامج أو مجلد أو ملف يصلح أيضًا)",
            "alwaysOnTop", "دائمًا في المقدمة",
            "whichPage", "إلى أي صفحة يُضاف",
            "refresh", "تحديث",
            "added", "المضاف",
            "close", "إغلاق",
            "iconYes", "  (أيقونة ✓)",
            "iconNo", "  (بدون أيقونة)",
            "hostNotRunning", "(المضيف لا يعمل)",
            "infoTitle", "surecut-deck: تفاصيل الخادم",
            "pairCodeLabel", "رمز الاقتران",
            "copyCode", "نسخ الرمز",
            "addressHint", "افتح أحد هذه العناوين على الجهاز اللوحي (نقر مزدوج للنسخ)",
            "colAddress", "العنوان",
            "colInterface", "واجهة الشبكة",
            "settingsTitle", "surecut-deck: الإعدادات",
            "port", "المنفذ",
            "portHint", "تغييره يعيد تشغيل المضيف ويغيّر العنوان على الجهاز اللوحي.",
            "startWithWindows", "التشغيل مع Windows",
            "startMinimized", "عدم فتح نافذة عند بدء التشغيل (منطقة الإعلام فقط)",
            "regenCode", "إنشاء رمز اقتران جديد",
            "regenHint", "ستُفصل الأجهزة اللوحية المتصلة وستحتاج إلى الرمز الجديد.",
            "addFirewall", "إضافة قاعدة جدار حماية (تتطلب صلاحيات المسؤول)",
            "save", "حفظ",
            "cancel", "إلغاء",
            "firewallAdded", "تمت إضافة قاعدة جدار الحماية (المنفذ ",
            "firewallAddedTail", "، ملف التعريف خاص).",
            "firewallFailed", "تعذّرت إضافة القاعدة. هل تمت الموافقة كمسؤول؟",
            "firewallError", "تعذّرت إضافة القاعدة: ",
            "logTitle", "surecut-deck: السجل",
            "dropHere", "أفلت اختصارًا من سطح المكتب في أي مكان داخل هذه النافذة: يُلتقط هدفه وأيقونته تلقائيًا",
            "dropNow", "أفلته",
            "uiFailed", "تعذّر تحميل الواجهة:\\r\\n",
            "uiFailedHint", "\\r\\n\\r\\nقد لا يكون وقت تشغيل WebView2 مثبتًا.\\r\\nيمكنك المتابعة عبر «فتح الواجهة في المتصفح» من قائمة منطقة الإعلام.",
            "buttonsAdded", " زر تمت إضافته"
        });

        Add("bn", new string[] {
            "alreadyRunning", "surecut-deck আগে থেকেই চলছে।",
            "running", "● চলছে  ·  পোর্ট ",
            "stopped", "○ থেমে আছে",
            "pairCode", "পেয়ারিং কোড:  ",
            "openEditor", "সম্পাদক খুলুন",
            "dragDrop", "শর্টকাট টেনে ছাড়ুন…",
            "serverInfo", "সার্ভারের বিবরণ…",
            "openInBrowser", "ইন্টারফেস ব্রাউজারে খুলুন",
            "copyAddress", "সংযোগের ঠিকানা কপি করুন",
            "settings", "সেটিংস…",
            "log", "লগ…",
            "restart", "আবার চালু করুন",
            "stop", "থামান",
            "start", "চালু করুন",
            "quit", "প্রস্থান",
            "nodeFailed", "Node.js চালু করা গেল না:\n\n",
            "nodeFailedHint", "\n\nNode.js ইনস্টল থাকতে হবে এবং PATH-এ থাকতে হবে।",
            "trayRunning", "surecut-deck: চলছে (পোর্ট ",
            "trayStopped", "surecut-deck: থেমে আছে",
            "notGenerated", "(এখনো তৈরি হয়নি)",
            "editorFellBack", "সম্পাদক উইন্ডো খোলা গেল না, বদলে ব্রাউজার ব্যবহার হচ্ছে। বিস্তারিত: লগ",
            "copied", "কপি হয়েছে: ",
            "newCode", "নতুন পেয়ারিং কোড: ",
            "newCodeHint", "\n\nট্যাবলেটের সংযোগ বিচ্ছিন্ন হবে এবং নতুন কোড লাগবে।",
            "autoStartFailed", "স্বয়ংক্রিয় চালু সেট করা গেল না: ",
            "dropTitle", "surecut-deck: টেনে ছাড়ুন",
            "dropZone", "ডেস্কটপ থেকে শর্টকাট টানুন\r\nএবং এখানে ছাড়ুন\r\n\r\n(প্রোগ্রাম, ফোল্ডার বা ফাইলও চলবে)",
            "alwaysOnTop", "সবসময় উপরে",
            "whichPage", "কোন পাতায় যোগ হবে",
            "refresh", "রিফ্রেশ",
            "added", "যোগ হয়েছে",
            "close", "বন্ধ",
            "iconYes", "  (আইকন ✓)",
            "iconNo", "  (আইকন নেই)",
            "hostNotRunning", "(হোস্ট চলছে না)",
            "infoTitle", "surecut-deck: সার্ভারের বিবরণ",
            "pairCodeLabel", "পেয়ারিং কোড",
            "copyCode", "কোড কপি করুন",
            "addressHint", "ট্যাবলেটে এর একটি খুলুন (কপি করতে ডবল ক্লিক)",
            "colAddress", "ঠিকানা",
            "colInterface", "নেটওয়ার্ক ইন্টারফেস",
            "settingsTitle", "surecut-deck: সেটিংস",
            "port", "পোর্ট",
            "portHint", "এটি বদলালে হোস্ট আবার চালু হয় এবং ট্যাবলেটের ঠিকানা বদলে যায়।",
            "startWithWindows", "Windows-এর সাথে চালু হবে",
            "startMinimized", "চালুর সময় উইন্ডো খুলবে না (শুধু ট্রে)",
            "regenCode", "পেয়ারিং কোড নতুন করে তৈরি করুন",
            "regenHint", "যুক্ত ট্যাবলেটগুলোর সংযোগ বিচ্ছিন্ন হবে এবং নতুন কোড লাগবে।",
            "addFirewall", "ফায়ারওয়াল নিয়ম যোগ করুন (অ্যাডমিন দরকার)",
            "save", "সংরক্ষণ",
            "cancel", "বাতিল",
            "firewallAdded", "ফায়ারওয়াল নিয়ম যোগ হয়েছে (পোর্ট ",
            "firewallAddedTail", ", ব্যক্তিগত প্রোফাইল)।",
            "firewallFailed", "নিয়মটি যোগ করা গেল না। অ্যাডমিন অনুমোদন দেওয়া হয়েছিল কি?",
            "firewallError", "নিয়মটি যোগ করা গেল না: ",
            "logTitle", "surecut-deck: লগ",
            "dropHere", "ডেস্কটপ থেকে শর্টকাট এই উইন্ডোর যেকোনো জায়গায় ছাড়ুন: এর লক্ষ্য ও আইকন নিজে থেকেই নেওয়া হয়",
            "dropNow", "ছেড়ে দিন",
            "uiFailed", "ইন্টারফেস লোড করা গেল না:\r\n",
            "uiFailedHint", "\r\n\r\nWebView2 রানটাইম ইনস্টল করা না থাকতে পারে।\r\nট্রে মেনু থেকে \"ইন্টারফেস ব্রাউজারে খুলুন\" দিয়ে চালিয়ে যেতে পারেন।",
            "buttonsAdded", " বোতাম যোগ হয়েছে"
        });

        Add("de", new string[] {
            "alreadyRunning", "surecut-deck läuft bereits.",
            "running", "● Läuft  ·  Port ",
            "stopped", "○ Gestoppt",
            "pairCode", "Kopplungscode:  ",
            "openEditor", "Editor öffnen",
            "dragDrop", "Verknüpfung ziehen und ablegen…",
            "serverInfo", "Serverdetails…",
            "openInBrowser", "Oberfläche im Browser öffnen",
            "copyAddress", "Verbindungsadresse kopieren",
            "settings", "Einstellungen…",
            "log", "Protokoll…",
            "restart", "Neu starten",
            "stop", "Stoppen",
            "start", "Starten",
            "quit", "Beenden",
            "nodeFailed", "Node.js konnte nicht gestartet werden:\n\n",
            "nodeFailedHint", "\n\nNode.js muss installiert und im PATH sein.",
            "trayRunning", "surecut-deck: läuft (Port ",
            "trayStopped", "surecut-deck: gestoppt",
            "notGenerated", "(noch nicht erzeugt)",
            "editorFellBack", "Das Editor-Fenster konnte nicht geöffnet werden, es wird der Browser verwendet. Details: Protokoll",
            "copied", "Kopiert: ",
            "newCode", "Neuer Kopplungscode: ",
            "newCodeHint", "\n\nDas Tablet wird getrennt und braucht den neuen Code.",
            "autoStartFailed", "Der automatische Start konnte nicht eingerichtet werden: ",
            "dropTitle", "surecut-deck: Ziehen und Ablegen",
            "dropZone", "Zieh eine Verknüpfung vom Desktop\r\nund lege sie hier ab\r\n\r\n(ein Programm, Ordner oder eine Datei geht auch)",
            "alwaysOnTop", "Immer im Vordergrund",
            "whichPage", "Zu welcher Seite hinzufügen",
            "refresh", "Aktualisieren",
            "added", "Hinzugefügt",
            "close", "Schließen",
            "iconYes", "  (Symbol ✓)",
            "iconNo", "  (kein Symbol)",
            "hostNotRunning", "(Host läuft nicht)",
            "infoTitle", "surecut-deck: Serverdetails",
            "pairCodeLabel", "Kopplungscode",
            "copyCode", "Code kopieren",
            "addressHint", "Öffne eine davon auf dem Tablet (Doppelklick zum Kopieren)",
            "colAddress", "Adresse",
            "colInterface", "Netzwerkschnittstelle",
            "settingsTitle", "surecut-deck: Einstellungen",
            "port", "Port",
            "portHint", "Eine Änderung startet den Host neu und ändert die Adresse auf dem Tablet.",
            "startWithWindows", "Mit Windows starten",
            "startMinimized", "Beim Start kein Fenster öffnen (nur Infobereich)",
            "regenCode", "Kopplungscode neu erzeugen",
            "regenHint", "Verbundene Tablets werden getrennt und brauchen den neuen Code.",
            "addFirewall", "Firewallregel hinzufügen (erfordert Administrator)",
            "save", "Speichern",
            "cancel", "Abbrechen",
            "firewallAdded", "Firewallregel hinzugefügt (Port ",
            "firewallAddedTail", ", Profil Privat).",
            "firewallFailed", "Die Regel konnte nicht hinzugefügt werden. Wurde die Administratorfreigabe erteilt?",
            "firewallError", "Die Regel konnte nicht hinzugefügt werden: ",
            "logTitle", "surecut-deck: Protokoll",
            "dropHere", "Lege eine Verknüpfung vom Desktop irgendwo in diesem Fenster ab: Ziel und Symbol werden automatisch übernommen",
            "dropNow", "Loslassen",
            "uiFailed", "Die Oberfläche konnte nicht geladen werden:\r\n",
            "uiFailedHint", "\r\n\r\nDie WebView2-Laufzeit ist möglicherweise nicht installiert.\r\nDu kannst mit „Oberfläche im Browser öffnen“ aus dem Infobereichsmenü fortfahren.",
            "buttonsAdded", " Schaltflächen hinzugefügt"
        });

        Add("es", new string[] {
            "alreadyRunning", "surecut-deck ya está en ejecución.",
            "running", "● En ejecución  ·  puerto ",
            "stopped", "○ Detenido",
            "pairCode", "Código de emparejamiento:  ",
            "openEditor", "Abrir editor",
            "dragDrop", "Arrastrar y soltar un acceso directo…",
            "serverInfo", "Detalles del servidor…",
            "openInBrowser", "Abrir la interfaz en el navegador",
            "copyAddress", "Copiar la dirección de conexión",
            "settings", "Configuración…",
            "log", "Registro…",
            "restart", "Reiniciar",
            "stop", "Detener",
            "start", "Iniciar",
            "quit", "Salir",
            "nodeFailed", "No se pudo iniciar Node.js:\n\n",
            "nodeFailedHint", "\n\nNode.js debe estar instalado y en el PATH.",
            "trayRunning", "surecut-deck: en ejecución (puerto ",
            "trayStopped", "surecut-deck: detenido",
            "notGenerated", "(aún no generado)",
            "editorFellBack", "No se pudo abrir la ventana del editor, se usará el navegador. Detalles: Registro",
            "copied", "Copiado: ",
            "newCode", "Nuevo código de emparejamiento: ",
            "newCodeHint", "\n\nLa tableta se desconectará y necesitará el nuevo código.",
            "autoStartFailed", "No se pudo configurar el inicio automático: ",
            "dropTitle", "surecut-deck: Arrastrar y soltar",
            "dropZone", "Arrastra un acceso directo del escritorio\r\ny suéltalo aquí\r\n\r\n(también vale un programa, carpeta o archivo)",
            "alwaysOnTop", "Siempre visible",
            "whichPage", "A qué página añadirlo",
            "refresh", "Actualizar",
            "added", "Añadidos",
            "close", "Cerrar",
            "iconYes", "  (icono ✓)",
            "iconNo", "  (sin icono)",
            "hostNotRunning", "(el host no está en ejecución)",
            "infoTitle", "surecut-deck: Detalles del servidor",
            "pairCodeLabel", "Código de emparejamiento",
            "copyCode", "Copiar código",
            "addressHint", "Abre una de estas en la tableta (doble clic para copiar)",
            "colAddress", "Dirección",
            "colInterface", "Interfaz de red",
            "settingsTitle", "surecut-deck: Configuración",
            "port", "Puerto",
            "portHint", "Al cambiarlo se reinicia el host y cambia la dirección en la tableta.",
            "startWithWindows", "Iniciar con Windows",
            "startMinimized", "No abrir ninguna ventana al iniciar (solo en la bandeja)",
            "regenCode", "Regenerar el código de emparejamiento",
            "regenHint", "Las tabletas conectadas se desconectarán y necesitarán el nuevo código.",
            "addFirewall", "Añadir una regla de firewall (requiere administrador)",
            "save", "Guardar",
            "cancel", "Cancelar",
            "firewallAdded", "Regla de firewall añadida (puerto ",
            "firewallAddedTail", ", perfil Privado).",
            "firewallFailed", "No se pudo añadir la regla. ¿Se dio la aprobación de administrador?",
            "firewallError", "No se pudo añadir la regla: ",
            "logTitle", "surecut-deck: Registro",
            "dropHere", "Suelta un acceso directo del escritorio en cualquier parte de esta ventana: su destino y su icono se toman automáticamente",
            "dropNow", "Suéltalo",
            "uiFailed", "No se pudo cargar la interfaz:\r\n",
            "uiFailedHint", "\r\n\r\nPuede que el entorno de ejecución WebView2 no esté instalado.\r\nPuedes continuar con \"Abrir la interfaz en el navegador\" desde el menú de la bandeja.",
            "buttonsAdded", " botones añadidos"
        });

        Add("fa", new string[] {
            "alreadyRunning", "surecut-deck از قبل در حال اجراست.",
            "running", "● در حال اجرا  ·  پورت ",
            "stopped", "○ متوقف",
            "pairCode", "کد جفت‌سازی:  ",
            "openEditor", "باز کردن ویرایشگر",
            "dragDrop", "کشیدن و رها کردن میان‌بر…",
            "serverInfo", "جزئیات سرور…",
            "openInBrowser", "باز کردن رابط در مرورگر",
            "copyAddress", "کپی نشانی اتصال",
            "settings", "تنظیمات…",
            "log", "گزارش…",
            "restart", "راه‌اندازی دوباره",
            "stop", "توقف",
            "start", "شروع",
            "quit", "خروج",
            "nodeFailed", "Node.js اجرا نشد:\n\n",
            "nodeFailedHint", "\n\nNode.js باید نصب و در PATH باشد.",
            "trayRunning", "surecut-deck: در حال اجرا (پورت ",
            "trayStopped", "surecut-deck: متوقف",
            "notGenerated", "(هنوز ساخته نشده)",
            "editorFellBack", "پنجرهٔ ویرایشگر باز نشد، به‌جای آن مرورگر استفاده می‌شود. جزئیات: گزارش",
            "copied", "کپی شد: ",
            "newCode", "کد جفت‌سازی جدید: ",
            "newCodeHint", "\n\nاتصال تبلت قطع می‌شود و به کد جدید نیاز خواهد داشت.",
            "autoStartFailed", "اجرای خودکار تنظیم نشد: ",
            "dropTitle", "surecut-deck: کشیدن و رها کردن",
            "dropZone", "میان‌بری را از میزکار بکشید\r\nو اینجا رها کنید\r\n\r\n(برنامه، پوشه یا پرونده هم می‌شود)",
            "alwaysOnTop", "همیشه در بالا",
            "whichPage", "افزودن به کدام صفحه",
            "refresh", "تازه‌سازی",
            "added", "افزوده‌شده‌ها",
            "close", "بستن",
            "iconYes", "  (نماد ✓)",
            "iconNo", "  (بدون نماد)",
            "hostNotRunning", "(میزبان در حال اجرا نیست)",
            "infoTitle", "surecut-deck: جزئیات سرور",
            "pairCodeLabel", "کد جفت‌سازی",
            "copyCode", "کپی کد",
            "addressHint", "یکی از این‌ها را روی تبلت باز کنید (برای کپی دوبار کلیک کنید)",
            "colAddress", "نشانی",
            "colInterface", "رابط شبکه",
            "settingsTitle", "surecut-deck: تنظیمات",
            "port", "پورت",
            "portHint", "تغییر آن میزبان را دوباره راه‌اندازی می‌کند و نشانی روی تبلت عوض می‌شود.",
            "startWithWindows", "اجرا هنگام راه‌اندازی Windows",
            "startMinimized", "هنگام شروع پنجره باز نشود (فقط در سینی)",
            "regenCode", "ساخت دوبارهٔ کد جفت‌سازی",
            "regenHint", "اتصال تبلت‌های متصل قطع می‌شود و به کد جدید نیاز دارند.",
            "addFirewall", "افزودن قاعدهٔ دیوار آتش (نیازمند مدیر)",
            "save", "ذخیره",
            "cancel", "انصراف",
            "firewallAdded", "قاعدهٔ دیوار آتش افزوده شد (پورت ",
            "firewallAddedTail", "، نمایهٔ خصوصی).",
            "firewallFailed", "قاعده افزوده نشد. تأیید مدیر داده شد؟",
            "firewallError", "قاعده افزوده نشد: ",
            "logTitle", "surecut-deck: گزارش",
            "dropHere", "میان‌بر را از میزکار در هر جای این پنجره رها کنید: هدف و نماد آن خودکار برداشته می‌شود",
            "dropNow", "رها کنید",
            "uiFailed", "رابط بارگذاری نشد:\r\n",
            "uiFailedHint", "\r\n\r\nممکن است زمان اجرای WebView2 نصب نباشد.\r\nمی‌توانید با «باز کردن رابط در مرورگر» از منوی سینی ادامه دهید.",
            "buttonsAdded", " دکمه افزوده شد"
        });

        Add("fr", new string[] {
            "alreadyRunning", "surecut-deck est déjà en cours d'exécution.",
            "running", "● En cours  ·  port ",
            "stopped", "○ Arrêté",
            "pairCode", "Code d'appairage :  ",
            "openEditor", "Ouvrir l'éditeur",
            "dragDrop", "Glisser-déposer un raccourci…",
            "serverInfo", "Détails du serveur…",
            "openInBrowser", "Ouvrir l'interface dans le navigateur",
            "copyAddress", "Copier l'adresse de connexion",
            "settings", "Paramètres…",
            "log", "Journal…",
            "restart", "Redémarrer",
            "stop", "Arrêter",
            "start", "Démarrer",
            "quit", "Quitter",
            "nodeFailed", "Node.js n'a pas pu être démarré :\n\n",
            "nodeFailedHint", "\n\nNode.js doit être installé et présent dans le PATH.",
            "trayRunning", "surecut-deck : en cours (port ",
            "trayStopped", "surecut-deck : arrêté",
            "notGenerated", "(pas encore généré)",
            "editorFellBack", "La fenêtre de l'éditeur n'a pas pu s'ouvrir, le navigateur est utilisé. Détails : Journal",
            "copied", "Copié : ",
            "newCode", "Nouveau code d'appairage : ",
            "newCodeHint", "\n\nLa tablette sera déconnectée et aura besoin du nouveau code.",
            "autoStartFailed", "Le démarrage automatique n'a pas pu être configuré : ",
            "dropTitle", "surecut-deck : Glisser-déposer",
            "dropZone", "Fais glisser un raccourci du bureau\r\net dépose-le ici\r\n\r\n(un programme, un dossier ou un fichier convient aussi)",
            "alwaysOnTop", "Toujours au premier plan",
            "whichPage", "Sur quelle page l'ajouter",
            "refresh", "Actualiser",
            "added", "Ajoutés",
            "close", "Fermer",
            "iconYes", "  (icône ✓)",
            "iconNo", "  (pas d'icône)",
            "hostNotRunning", "(hôte non démarré)",
            "infoTitle", "surecut-deck : Détails du serveur",
            "pairCodeLabel", "Code d'appairage",
            "copyCode", "Copier le code",
            "addressHint", "Ouvre l'une de ces adresses sur la tablette (double clic pour copier)",
            "colAddress", "Adresse",
            "colInterface", "Interface réseau",
            "settingsTitle", "surecut-deck : Paramètres",
            "port", "Port",
            "portHint", "Le modifier redémarre l'hôte et change l'adresse sur la tablette.",
            "startWithWindows", "Démarrer avec Windows",
            "startMinimized", "Ne pas ouvrir de fenêtre au démarrage (zone de notification seulement)",
            "regenCode", "Régénérer le code d'appairage",
            "regenHint", "Les tablettes connectées seront déconnectées et auront besoin du nouveau code.",
            "addFirewall", "Ajouter une règle de pare-feu (nécessite l'administrateur)",
            "save", "Enregistrer",
            "cancel", "Annuler",
            "firewallAdded", "Règle de pare-feu ajoutée (port ",
            "firewallAddedTail", ", profil Privé).",
            "firewallFailed", "La règle n'a pas pu être ajoutée. L'approbation administrateur a-t-elle été donnée ?",
            "firewallError", "La règle n'a pas pu être ajoutée : ",
            "logTitle", "surecut-deck : Journal",
            "dropHere", "Dépose un raccourci du bureau n'importe où dans cette fenêtre : sa cible et son icône sont reprises automatiquement",
            "dropNow", "Dépose-le",
            "uiFailed", "L'interface n'a pas pu se charger :\r\n",
            "uiFailedHint", "\r\n\r\nLe runtime WebView2 n'est peut-être pas installé.\r\nTu peux continuer avec « Ouvrir l'interface dans le navigateur » depuis le menu de la zone de notification.",
            "buttonsAdded", " boutons ajoutés"
        });

        Add("hi", new string[] {
            "alreadyRunning", "surecut-deck पहले से चल रहा है।",
            "running", "● चल रहा है  ·  पोर्ट ",
            "stopped", "○ रुका हुआ",
            "pairCode", "पेयरिंग कोड:  ",
            "openEditor", "एडिटर खोलें",
            "dragDrop", "शॉर्टकट खींचें और छोड़ें…",
            "serverInfo", "सर्वर विवरण…",
            "openInBrowser", "इंटरफ़ेस ब्राउज़र में खोलें",
            "copyAddress", "कनेक्शन का पता कॉपी करें",
            "settings", "सेटिंग्स…",
            "log", "लॉग…",
            "restart", "फिर से शुरू करें",
            "stop", "रोकें",
            "start", "शुरू करें",
            "quit", "बाहर निकलें",
            "nodeFailed", "Node.js शुरू नहीं हो सका:\n\n",
            "nodeFailedHint", "\n\nNode.js इंस्टॉल और PATH में होना चाहिए।",
            "trayRunning", "surecut-deck: चल रहा है (पोर्ट ",
            "trayStopped", "surecut-deck: रुका हुआ",
            "notGenerated", "(अभी बना नहीं)",
            "editorFellBack", "एडिटर विंडो नहीं खुल सकी, इसके बजाय ब्राउज़र इस्तेमाल हो रहा है। विवरण: लॉग",
            "copied", "कॉपी हुआ: ",
            "newCode", "नया पेयरिंग कोड: ",
            "newCodeHint", "\n\nटैबलेट का कनेक्शन टूट जाएगा और उसे नया कोड चाहिए होगा।",
            "autoStartFailed", "स्वचालित शुरुआत सेट नहीं हो सकी: ",
            "dropTitle", "surecut-deck: खींचें और छोड़ें",
            "dropZone", "डेस्कटॉप से शॉर्टकट खींचें\r\nऔर यहाँ छोड़ें\r\n\r\n(प्रोग्राम, फ़ोल्डर या फ़ाइल भी चलेगी)",
            "alwaysOnTop", "हमेशा सबसे ऊपर",
            "whichPage", "किस पेज में जोड़ें",
            "refresh", "रीफ़्रेश",
            "added", "जोड़े गए",
            "close", "बंद करें",
            "iconYes", "  (आइकन ✓)",
            "iconNo", "  (आइकन नहीं)",
            "hostNotRunning", "(होस्ट नहीं चल रहा)",
            "infoTitle", "surecut-deck: सर्वर विवरण",
            "pairCodeLabel", "पेयरिंग कोड",
            "copyCode", "कोड कॉपी करें",
            "addressHint", "टैबलेट पर इनमें से एक खोलें (कॉपी करने के लिए डबल क्लिक)",
            "colAddress", "पता",
            "colInterface", "नेटवर्क इंटरफ़ेस",
            "settingsTitle", "surecut-deck: सेटिंग्स",
            "port", "पोर्ट",
            "portHint", "इसे बदलने पर होस्ट फिर से शुरू होता है और टैबलेट पर पता बदल जाता है।",
            "startWithWindows", "Windows के साथ शुरू करें",
            "startMinimized", "शुरू होते समय विंडो न खोलें (सिर्फ़ ट्रे)",
            "regenCode", "पेयरिंग कोड फिर से बनाएँ",
            "regenHint", "जुड़े हुए टैबलेट डिस्कनेक्ट हो जाएँगे और उन्हें नया कोड चाहिए होगा।",
            "addFirewall", "फ़ायरवॉल नियम जोड़ें (एडमिन चाहिए)",
            "save", "सहेजें",
            "cancel", "रद्द करें",
            "firewallAdded", "फ़ायरवॉल नियम जुड़ गया (पोर्ट ",
            "firewallAddedTail", ", निजी प्रोफ़ाइल)।",
            "firewallFailed", "नियम नहीं जोड़ा जा सका। क्या एडमिन की मंज़ूरी दी गई थी?",
            "firewallError", "नियम नहीं जोड़ा जा सका: ",
            "logTitle", "surecut-deck: लॉग",
            "dropHere", "डेस्कटॉप से शॉर्टकट इस विंडो में कहीं भी छोड़ें: उसका लक्ष्य और आइकन अपने आप ले लिया जाता है",
            "dropNow", "छोड़ दें",
            "uiFailed", "इंटरफ़ेस लोड नहीं हो सका:\r\n",
            "uiFailedHint", "\r\n\r\nहो सकता है WebView2 रनटाइम इंस्टॉल न हो।\r\nआप ट्रे मेन्यू से \"इंटरफ़ेस ब्राउज़र में खोलें\" के साथ जारी रख सकते हैं।",
            "buttonsAdded", " बटन जोड़े गए"
        });

        Add("id", new string[] {
            "alreadyRunning", "surecut-deck sudah berjalan.",
            "running", "● Berjalan  ·  port ",
            "stopped", "○ Berhenti",
            "pairCode", "Kode pemasangan:  ",
            "openEditor", "Buka Editor",
            "dragDrop", "Seret dan Lepas Pintasan…",
            "serverInfo", "Detail Server…",
            "openInBrowser", "Buka Antarmuka di Peramban",
            "copyAddress", "Salin Alamat Sambungan",
            "settings", "Pengaturan…",
            "log", "Log…",
            "restart", "Mulai Ulang",
            "stop", "Hentikan",
            "start", "Mulai",
            "quit", "Keluar",
            "nodeFailed", "Node.js tidak bisa dijalankan:\n\n",
            "nodeFailedHint", "\n\nNode.js harus terpasang dan ada di PATH.",
            "trayRunning", "surecut-deck: berjalan (port ",
            "trayStopped", "surecut-deck: berhenti",
            "notGenerated", "(belum dibuat)",
            "editorFellBack", "Jendela editor tidak bisa dibuka, memakai peramban. Rincian: Log",
            "copied", "Disalin: ",
            "newCode", "Kode pemasangan baru: ",
            "newCodeHint", "\n\nSambungan tablet akan terputus dan tablet perlu kode yang baru.",
            "autoStartFailed", "Mulai otomatis tidak bisa diatur: ",
            "dropTitle", "surecut-deck: Seret dan Lepas",
            "dropZone", "Seret pintasan dari desktop\r\ndan lepaskan di sini\r\n\r\n(program, folder atau berkas juga bisa)",
            "alwaysOnTop", "Selalu di atas",
            "whichPage", "Ditambahkan ke halaman mana",
            "refresh", "Segarkan",
            "added", "Ditambahkan",
            "close", "Tutup",
            "iconYes", "  (ikon ✓)",
            "iconNo", "  (tanpa ikon)",
            "hostNotRunning", "(host tidak berjalan)",
            "infoTitle", "surecut-deck: Detail Server",
            "pairCodeLabel", "Kode pemasangan",
            "copyCode", "Salin Kode",
            "addressHint", "Buka salah satunya di tablet (klik dua kali untuk menyalin)",
            "colAddress", "Alamat",
            "colInterface", "Antarmuka jaringan",
            "settingsTitle", "surecut-deck: Pengaturan",
            "port", "Port",
            "portHint", "Mengubahnya akan memulai ulang host dan mengubah alamat di tablet.",
            "startWithWindows", "Mulai bersama Windows",
            "startMinimized", "Jangan buka jendela saat mulai (hanya di area notifikasi)",
            "regenCode", "Buat ulang kode pemasangan",
            "regenHint", "Tablet yang tersambung akan terputus dan perlu kode yang baru.",
            "addFirewall", "Tambahkan aturan firewall (perlu administrator)",
            "save", "Simpan",
            "cancel", "Batal",
            "firewallAdded", "Aturan firewall ditambahkan (port ",
            "firewallAddedTail", ", profil Privat).",
            "firewallFailed", "Aturan tidak bisa ditambahkan. Apakah persetujuan administrator diberikan?",
            "firewallError", "Aturan tidak bisa ditambahkan: ",
            "logTitle", "surecut-deck: Log",
            "dropHere", "Lepaskan pintasan dari desktop di mana saja pada jendela ini: sasaran dan ikonnya diambil otomatis",
            "dropNow", "Lepaskan",
            "uiFailed", "Antarmuka tidak bisa dimuat:\r\n",
            "uiFailedHint", "\r\n\r\nRuntime WebView2 mungkin belum terpasang.\r\nAnda bisa lanjut dengan \"Buka Antarmuka di Peramban\" dari menu area notifikasi.",
            "buttonsAdded", " tombol ditambahkan"
        });

        Add("it", new string[] {
            "alreadyRunning", "surecut-deck è già in esecuzione.",
            "running", "● In esecuzione  ·  porta ",
            "stopped", "○ Arrestato",
            "pairCode", "Codice di associazione:  ",
            "openEditor", "Apri editor",
            "dragDrop", "Trascina e rilascia un collegamento…",
            "serverInfo", "Dettagli del server…",
            "openInBrowser", "Apri l'interfaccia nel browser",
            "copyAddress", "Copia l'indirizzo di connessione",
            "settings", "Impostazioni…",
            "log", "Registro…",
            "restart", "Riavvia",
            "stop", "Arresta",
            "start", "Avvia",
            "quit", "Esci",
            "nodeFailed", "Impossibile avviare Node.js:\n\n",
            "nodeFailedHint", "\n\nNode.js deve essere installato e presente nel PATH.",
            "trayRunning", "surecut-deck: in esecuzione (porta ",
            "trayStopped", "surecut-deck: arrestato",
            "notGenerated", "(non ancora generato)",
            "editorFellBack", "Impossibile aprire la finestra dell'editor, viene usato il browser. Dettagli: Registro",
            "copied", "Copiato: ",
            "newCode", "Nuovo codice di associazione: ",
            "newCodeHint", "\n\nIl tablet verrà disconnesso e avrà bisogno del nuovo codice.",
            "autoStartFailed", "Impossibile impostare l'avvio automatico: ",
            "dropTitle", "surecut-deck: Trascina e rilascia",
            "dropZone", "Trascina un collegamento dal desktop\r\ne rilascialo qui\r\n\r\n(va bene anche un programma, una cartella o un file)",
            "alwaysOnTop", "Sempre in primo piano",
            "whichPage", "In quale pagina aggiungerlo",
            "refresh", "Aggiorna",
            "added", "Aggiunti",
            "close", "Chiudi",
            "iconYes", "  (icona ✓)",
            "iconNo", "  (nessuna icona)",
            "hostNotRunning", "(host non in esecuzione)",
            "infoTitle", "surecut-deck: Dettagli del server",
            "pairCodeLabel", "Codice di associazione",
            "copyCode", "Copia codice",
            "addressHint", "Apri uno di questi sul tablet (doppio clic per copiare)",
            "colAddress", "Indirizzo",
            "colInterface", "Interfaccia di rete",
            "settingsTitle", "surecut-deck: Impostazioni",
            "port", "Porta",
            "portHint", "Modificandola l'host si riavvia e l'indirizzo sul tablet cambia.",
            "startWithWindows", "Avvia con Windows",
            "startMinimized", "Non aprire nessuna finestra all'avvio (solo area di notifica)",
            "regenCode", "Rigenera il codice di associazione",
            "regenHint", "I tablet connessi verranno disconnessi e avranno bisogno del nuovo codice.",
            "addFirewall", "Aggiungi una regola del firewall (richiede l'amministratore)",
            "save", "Salva",
            "cancel", "Annulla",
            "firewallAdded", "Regola del firewall aggiunta (porta ",
            "firewallAddedTail", ", profilo Privato).",
            "firewallFailed", "Impossibile aggiungere la regola. È stata data l'approvazione come amministratore?",
            "firewallError", "Impossibile aggiungere la regola: ",
            "logTitle", "surecut-deck: Registro",
            "dropHere", "Rilascia un collegamento dal desktop in un punto qualsiasi di questa finestra: destinazione e icona vengono presi automaticamente",
            "dropNow", "Rilascialo",
            "uiFailed", "Impossibile caricare l'interfaccia:\r\n",
            "uiFailedHint", "\r\n\r\nIl runtime WebView2 potrebbe non essere installato.\r\nPuoi continuare con \"Apri l'interfaccia nel browser\" dal menu dell'area di notifica.",
            "buttonsAdded", " pulsanti aggiunti"
        });

        Add("ja", new string[] {
            "alreadyRunning", "surecut-deck は既に実行されています。",
            "running", "● 実行中  ·  ポート ",
            "stopped", "○ 停止",
            "pairCode", "ペアリングコード：  ",
            "openEditor", "エディターを開く",
            "dragDrop", "ショートカットをドラッグ＆ドロップ…",
            "serverInfo", "サーバーの詳細…",
            "openInBrowser", "ブラウザーで画面を開く",
            "copyAddress", "接続アドレスをコピー",
            "settings", "設定…",
            "log", "ログ…",
            "restart", "再起動",
            "stop", "停止",
            "start", "開始",
            "quit", "終了",
            "nodeFailed", "Node.js を開始できませんでした：\n\n",
            "nodeFailedHint", "\n\nNode.js がインストールされ、PATH に含まれている必要があります。",
            "trayRunning", "surecut-deck: 実行中 (ポート ",
            "trayStopped", "surecut-deck: 停止",
            "notGenerated", "(まだ生成されていません)",
            "editorFellBack", "エディターウィンドウを開けなかったため、ブラウザーを使用します。詳細: ログ",
            "copied", "コピーしました: ",
            "newCode", "新しいペアリングコード: ",
            "newCodeHint", "\n\nタブレットの接続は切断され、新しいコードの入力が必要になります。",
            "autoStartFailed", "自動開始を設定できませんでした: ",
            "dropTitle", "surecut-deck: ドラッグ＆ドロップ",
            "dropZone", "デスクトップのショートカットを\r\nここにドラッグ＆ドロップ\r\n\r\n(プログラム、フォルダー、ファイルでも可)",
            "alwaysOnTop", "常に手前に表示",
            "whichPage", "追加先のページ",
            "refresh", "更新",
            "added", "追加済み",
            "close", "閉じる",
            "iconYes", "  (アイコン ✓)",
            "iconNo", "  (アイコンなし)",
            "hostNotRunning", "(ホストが実行されていません)",
            "infoTitle", "surecut-deck: サーバーの詳細",
            "pairCodeLabel", "ペアリングコード",
            "copyCode", "コードをコピー",
            "addressHint", "タブレットでいずれかを開いてください (ダブルクリックでコピー)",
            "colAddress", "アドレス",
            "colInterface", "ネットワーク インターフェイス",
            "settingsTitle", "surecut-deck: 設定",
            "port", "ポート",
            "portHint", "変更するとホストが再起動し、タブレット側のアドレスも変わります。",
            "startWithWindows", "Windows 起動時に開始する",
            "startMinimized", "起動時にウィンドウを開かない (通知領域のみ)",
            "regenCode", "ペアリングコードを再生成する",
            "regenHint", "接続中のタブレットは切断され、新しいコードの入力が必要になります。",
            "addFirewall", "ファイアウォールの規則を追加 (管理者権限が必要)",
            "save", "保存",
            "cancel", "キャンセル",
            "firewallAdded", "ファイアウォールの規則を追加しました (ポート ",
            "firewallAddedTail", "、プライベート プロファイル)。",
            "firewallFailed", "規則を追加できませんでした。管理者の承認は行われましたか？",
            "firewallError", "規則を追加できませんでした: ",
            "logTitle", "surecut-deck: ログ",
            "dropHere", "デスクトップのショートカットをこのウィンドウのどこにでもドロップしてください。対象とアイコンは自動的に取得されます",
            "dropNow", "ここにドロップ",
            "uiFailed", "画面を読み込めませんでした:\r\n",
            "uiFailedHint", "\r\n\r\nWebView2 ランタイムがインストールされていない可能性があります。\r\n通知領域のメニューの「ブラウザーで画面を開く」から続行できます。",
            "buttonsAdded", " 個のボタンを追加しました"
        });

        Add("ko", new string[] {
            "alreadyRunning", "surecut-deck이(가) 이미 실행 중입니다.",
            "running", "● 실행 중  ·  포트 ",
            "stopped", "○ 중지됨",
            "pairCode", "페어링 코드:  ",
            "openEditor", "편집기 열기",
            "dragDrop", "바로 가기 끌어다 놓기…",
            "serverInfo", "서버 정보…",
            "openInBrowser", "브라우저에서 화면 열기",
            "copyAddress", "연결 주소 복사",
            "settings", "설정…",
            "log", "로그…",
            "restart", "다시 시작",
            "stop", "중지",
            "start", "시작",
            "quit", "끝내기",
            "nodeFailed", "Node.js를 시작할 수 없습니다:\n\n",
            "nodeFailedHint", "\n\nNode.js가 설치되어 있고 PATH에 있어야 합니다.",
            "trayRunning", "surecut-deck: 실행 중 (포트 ",
            "trayStopped", "surecut-deck: 중지됨",
            "notGenerated", "(아직 생성되지 않음)",
            "editorFellBack", "편집기 창을 열 수 없어 브라우저를 사용합니다. 자세한 내용: 로그",
            "copied", "복사됨: ",
            "newCode", "새 페어링 코드: ",
            "newCodeHint", "\n\n태블릿의 연결이 끊어지며 새 코드를 입력해야 합니다.",
            "autoStartFailed", "자동 시작을 설정할 수 없습니다: ",
            "dropTitle", "surecut-deck: 끌어다 놓기",
            "dropZone", "바탕 화면의 바로 가기를\r\n여기에 끌어다 놓으세요\r\n\r\n(프로그램, 폴더, 파일도 됩니다)",
            "alwaysOnTop", "항상 위",
            "whichPage", "추가할 페이지",
            "refresh", "새로 고침",
            "added", "추가됨",
            "close", "닫기",
            "iconYes", "  (아이콘 ✓)",
            "iconNo", "  (아이콘 없음)",
            "hostNotRunning", "(호스트가 실행되지 않음)",
            "infoTitle", "surecut-deck: 서버 정보",
            "pairCodeLabel", "페어링 코드",
            "copyCode", "코드 복사",
            "addressHint", "태블릿에서 이 중 하나를 여세요 (두 번 클릭하면 복사)",
            "colAddress", "주소",
            "colInterface", "네트워크 인터페이스",
            "settingsTitle", "surecut-deck: 설정",
            "port", "포트",
            "portHint", "이 값을 바꾸면 호스트가 다시 시작되고 태블릿의 주소도 바뀝니다.",
            "startWithWindows", "Windows 시작 시 실행",
            "startMinimized", "시작할 때 창 열지 않음 (알림 영역만)",
            "regenCode", "페어링 코드 다시 생성",
            "regenHint", "연결된 태블릿의 연결이 끊어지며 새 코드를 입력해야 합니다.",
            "addFirewall", "방화벽 규칙 추가 (관리자 권한 필요)",
            "save", "저장",
            "cancel", "취소",
            "firewallAdded", "방화벽 규칙을 추가했습니다 (포트 ",
            "firewallAddedTail", ", 개인 프로필).",
            "firewallFailed", "규칙을 추가할 수 없습니다. 관리자 권한을 승인하셨습니까?",
            "firewallError", "규칙을 추가할 수 없습니다: ",
            "logTitle", "surecut-deck: 로그",
            "dropHere", "바탕 화면의 바로 가기를 이 창 아무 곳에나 놓으세요. 대상과 아이콘을 자동으로 가져옵니다",
            "dropNow", "여기에 놓으세요",
            "uiFailed", "화면을 불러올 수 없습니다:\r\n",
            "uiFailedHint", "\r\n\r\nWebView2 런타임이 설치되어 있지 않을 수 있습니다.\r\n알림 영역 메뉴의 \"브라우저에서 화면 열기\"로 계속할 수 있습니다.",
            "buttonsAdded", " 개의 버튼을 추가했습니다"
        });

        Add("pl", new string[] {
            "alreadyRunning", "surecut-deck jest już uruchomiony.",
            "running", "● Działa  ·  port ",
            "stopped", "○ Zatrzymany",
            "pairCode", "Kod parowania:  ",
            "openEditor", "Otwórz edytor",
            "dragDrop", "Przeciągnij i upuść skrót…",
            "serverInfo", "Szczegóły serwera…",
            "openInBrowser", "Otwórz interfejs w przeglądarce",
            "copyAddress", "Kopiuj adres połączenia",
            "settings", "Ustawienia…",
            "log", "Dziennik…",
            "restart", "Uruchom ponownie",
            "stop", "Zatrzymaj",
            "start", "Uruchom",
            "quit", "Zakończ",
            "nodeFailed", "Nie udało się uruchomić Node.js:\\n\\n",
            "nodeFailedHint", "\\n\\nNode.js musi być zainstalowany i dostępny w PATH.",
            "trayRunning", "surecut-deck: działa (port ",
            "trayStopped", "surecut-deck: zatrzymany",
            "notGenerated", "(jeszcze nie wygenerowano)",
            "editorFellBack", "Nie udało się otworzyć okna edytora, używana jest przeglądarka. Szczegóły: Dziennik",
            "copied", "Skopiowano: ",
            "newCode", "Nowy kod parowania: ",
            "newCodeHint", "\\n\\nTablet zostanie rozłączony i będzie potrzebował nowego kodu.",
            "autoStartFailed", "Nie udało się skonfigurować automatycznego uruchamiania: ",
            "dropTitle", "surecut-deck: przeciągnij i upuść",
            "dropZone", "Przeciągnij skrót z pulpitu\\r\\ni upuść go tutaj\\r\\n\\r\\n(program, folder lub plik też zadziała)",
            "alwaysOnTop", "Zawsze na wierzchu",
            "whichPage", "Na którą stronę dodać",
            "refresh", "Odśwież",
            "added", "Dodano",
            "close", "Zamknij",
            "iconYes", "  (ikona ✓)",
            "iconNo", "  (bez ikony)",
            "hostNotRunning", "(host nie działa)",
            "infoTitle", "surecut-deck: szczegóły serwera",
            "pairCodeLabel", "Kod parowania",
            "copyCode", "Kopiuj kod",
            "addressHint", "Otwórz jeden z tych adresów na tablecie (dwukrotne kliknięcie kopiuje)",
            "colAddress", "Adres",
            "colInterface", "Interfejs sieciowy",
            "settingsTitle", "surecut-deck: ustawienia",
            "port", "Port",
            "portHint", "Zmiana spowoduje ponowne uruchomienie hosta i zmianę adresu na tablecie.",
            "startWithWindows", "Uruchamiaj razem z systemem Windows",
            "startMinimized", "Nie otwieraj okna przy starcie (tylko zasobnik systemowy)",
            "regenCode", "Wygeneruj nowy kod parowania",
            "regenHint", "Podłączone tablety zostaną rozłączone i będą potrzebowały nowego kodu.",
            "addFirewall", "Dodaj regułę zapory (wymaga uprawnień administratora)",
            "save", "Zapisz",
            "cancel", "Anuluj",
            "firewallAdded", "Reguła zapory dodana (port ",
            "firewallAddedTail", ", profil Prywatny).",
            "firewallFailed", "Nie udało się dodać reguły. Czy zgoda administratora została udzielona?",
            "firewallError", "Nie udało się dodać reguły: ",
            "logTitle", "surecut-deck: dziennik",
            "dropHere", "Upuść skrót z pulpitu w dowolnym miejscu tego okna: jego cel i ikona zostaną pobrane automatycznie",
            "dropNow", "Upuść",
            "uiFailed", "Nie udało się załadować interfejsu:\\r\\n",
            "uiFailedHint", "\\r\\n\\r\\nŚrodowisko WebView2 może nie być zainstalowane.\\r\\nMożesz kontynuować, wybierając „Otwórz interfejs w przeglądarce” z menu zasobnika.",
            "buttonsAdded", " przycisków dodano"
        });

        Add("pt", new string[] {
            "alreadyRunning", "O surecut-deck já está em execução.",
            "running", "● Em execução  ·  porta ",
            "stopped", "○ Parado",
            "pairCode", "Código de emparelhamento:  ",
            "openEditor", "Abrir editor",
            "dragDrop", "Arrastar e largar um atalho…",
            "serverInfo", "Detalhes do servidor…",
            "openInBrowser", "Abrir a interface no navegador",
            "copyAddress", "Copiar o endereço de ligação",
            "settings", "Definições…",
            "log", "Registo…",
            "restart", "Reiniciar",
            "stop", "Parar",
            "start", "Iniciar",
            "quit", "Sair",
            "nodeFailed", "Não foi possível iniciar o Node.js:\n\n",
            "nodeFailedHint", "\n\nO Node.js tem de estar instalado e no PATH.",
            "trayRunning", "surecut-deck: em execução (porta ",
            "trayStopped", "surecut-deck: parado",
            "notGenerated", "(ainda não gerado)",
            "editorFellBack", "Não foi possível abrir a janela do editor, a usar o navegador. Detalhes: Registo",
            "copied", "Copiado: ",
            "newCode", "Novo código de emparelhamento: ",
            "newCodeHint", "\n\nO tablet será desligado e precisará do novo código.",
            "autoStartFailed", "Não foi possível configurar o arranque automático: ",
            "dropTitle", "surecut-deck: Arrastar e largar",
            "dropZone", "Arraste um atalho do ambiente de trabalho\r\ne largue-o aqui\r\n\r\n(um programa, pasta ou ficheiro também serve)",
            "alwaysOnTop", "Sempre visível",
            "whichPage", "A que página adicionar",
            "refresh", "Atualizar",
            "added", "Adicionados",
            "close", "Fechar",
            "iconYes", "  (ícone ✓)",
            "iconNo", "  (sem ícone)",
            "hostNotRunning", "(host não está em execução)",
            "infoTitle", "surecut-deck: Detalhes do servidor",
            "pairCodeLabel", "Código de emparelhamento",
            "copyCode", "Copiar código",
            "addressHint", "Abra um destes no tablet (duplo clique para copiar)",
            "colAddress", "Endereço",
            "colInterface", "Interface de rede",
            "settingsTitle", "surecut-deck: Definições",
            "port", "Porta",
            "portHint", "Alterá-la reinicia o host e muda o endereço no tablet.",
            "startWithWindows", "Iniciar com o Windows",
            "startMinimized", "Não abrir nenhuma janela ao arrancar (apenas na área de notificação)",
            "regenCode", "Gerar novo código de emparelhamento",
            "regenHint", "Os tablets ligados serão desligados e precisarão do novo código.",
            "addFirewall", "Adicionar uma regra da firewall (requer administrador)",
            "save", "Guardar",
            "cancel", "Cancelar",
            "firewallAdded", "Regra da firewall adicionada (porta ",
            "firewallAddedTail", ", perfil Privado).",
            "firewallFailed", "Não foi possível adicionar a regra. Foi dada a aprovação de administrador?",
            "firewallError", "Não foi possível adicionar a regra: ",
            "logTitle", "surecut-deck: Registo",
            "dropHere", "Largue um atalho do ambiente de trabalho em qualquer ponto desta janela: o destino e o ícone são obtidos automaticamente",
            "dropNow", "Largue aqui",
            "uiFailed", "Não foi possível carregar a interface:\r\n",
            "uiFailedHint", "\r\n\r\nO runtime WebView2 pode não estar instalado.\r\nPode continuar com \"Abrir a interface no navegador\" a partir do menu da área de notificação.",
            "buttonsAdded", " botões adicionados"
        });

        Add("ru", new string[] {
            "alreadyRunning", "surecut-deck уже запущен.",
            "running", "● Работает  ·  порт ",
            "stopped", "○ Остановлен",
            "pairCode", "Код сопряжения:  ",
            "openEditor", "Открыть редактор",
            "dragDrop", "Перетащить ярлык…",
            "serverInfo", "Сведения о сервере…",
            "openInBrowser", "Открыть интерфейс в браузере",
            "copyAddress", "Копировать адрес подключения",
            "settings", "Параметры…",
            "log", "Журнал…",
            "restart", "Перезапустить",
            "stop", "Остановить",
            "start", "Запустить",
            "quit", "Выход",
            "nodeFailed", "Не удалось запустить Node.js:\\n\\n",
            "nodeFailedHint", "\\n\\nNode.js должен быть установлен и находиться в PATH.",
            "trayRunning", "surecut-deck: работает (порт ",
            "trayStopped", "surecut-deck: остановлен",
            "notGenerated", "(ещё не создан)",
            "editorFellBack", "Не удалось открыть окно редактора, используется браузер. Подробности: Журнал",
            "copied", "Скопировано: ",
            "newCode", "Новый код сопряжения: ",
            "newCodeHint", "\\n\\nПланшет будет отключён, потребуется ввести новый код.",
            "autoStartFailed", "Не удалось настроить автозапуск: ",
            "dropTitle", "surecut-deck: перетаскивание",
            "dropZone", "Перетащите ярлык с рабочего стола\\r\\nи отпустите здесь\\r\\n\\r\\n(программа, папка или файл тоже подойдут)",
            "alwaysOnTop", "Поверх остальных окон",
            "whichPage", "На какую страницу добавить",
            "refresh", "Обновить",
            "added", "Добавлено",
            "close", "Закрыть",
            "iconYes", "  (значок ✓)",
            "iconNo", "  (без значка)",
            "hostNotRunning", "(хост не запущен)",
            "infoTitle", "surecut-deck: сведения о сервере",
            "pairCodeLabel", "Код сопряжения",
            "copyCode", "Копировать код",
            "addressHint", "Откройте один из этих адресов на планшете (двойной клик копирует)",
            "colAddress", "Адрес",
            "colInterface", "Сетевой интерфейс",
            "settingsTitle", "surecut-deck: параметры",
            "port", "Порт",
            "portHint", "Изменение перезапустит хост и изменит адрес на планшете.",
            "startWithWindows", "Запускать вместе с Windows",
            "startMinimized", "Не открывать окно при запуске (только в области уведомлений)",
            "regenCode", "Создать новый код сопряжения",
            "regenHint", "Подключённые планшеты будут отключены, потребуется ввести новый код.",
            "addFirewall", "Добавить правило брандмауэра (нужны права администратора)",
            "save", "Сохранить",
            "cancel", "Отмена",
            "firewallAdded", "Правило брандмауэра добавлено (порт ",
            "firewallAddedTail", ", профиль «Частный»).",
            "firewallFailed", "Не удалось добавить правило. Было ли дано подтверждение администратора?",
            "firewallError", "Не удалось добавить правило: ",
            "logTitle", "surecut-deck: журнал",
            "dropHere", "Перетащите ярлык с рабочего стола в любое место этого окна: цель и значок определяются автоматически",
            "dropNow", "Отпустите",
            "uiFailed", "Не удалось загрузить интерфейс:\\r\\n",
            "uiFailedHint", "\\r\\n\\r\\nВозможно, не установлена среда выполнения WebView2.\\r\\nМожно продолжить через «Открыть интерфейс в браузере» в меню области уведомлений.",
            "buttonsAdded", " кнопок добавлено"
        });

        Add("uk", new string[] {
            "alreadyRunning", "surecut-deck уже запущено.",
            "running", "● Працює  ·  порт ",
            "stopped", "○ Зупинено",
            "pairCode", "Код підключення:  ",
            "openEditor", "Відкрити редактор",
            "dragDrop", "Перетягнути ярлик…",
            "serverInfo", "Відомості про сервер…",
            "openInBrowser", "Відкрити інтерфейс у браузері",
            "copyAddress", "Копіювати адресу підключення",
            "settings", "Параметри…",
            "log", "Журнал…",
            "restart", "Перезапустити",
            "stop", "Зупинити",
            "start", "Запустити",
            "quit", "Вихід",
            "nodeFailed", "Не вдалося запустити Node.js:\\n\\n",
            "nodeFailedHint", "\\n\\nNode.js має бути встановлений і доступний у PATH.",
            "trayRunning", "surecut-deck: працює (порт ",
            "trayStopped", "surecut-deck: зупинено",
            "notGenerated", "(ще не створено)",
            "editorFellBack", "Не вдалося відкрити вікно редактора, використовується браузер. Подробиці: Журнал",
            "copied", "Скопійовано: ",
            "newCode", "Новий код підключення: ",
            "newCodeHint", "\\n\\nПланшет буде відключено, знадобиться новий код.",
            "autoStartFailed", "Не вдалося налаштувати автозапуск: ",
            "dropTitle", "surecut-deck: перетягування",
            "dropZone", "Перетягніть ярлик з робочого стола\\r\\nі відпустіть тут\\r\\n\\r\\n(програма, тека або файл теж підійдуть)",
            "alwaysOnTop", "Поверх інших вікон",
            "whichPage", "На яку сторінку додати",
            "refresh", "Оновити",
            "added", "Додано",
            "close", "Закрити",
            "iconYes", "  (значок ✓)",
            "iconNo", "  (без значка)",
            "hostNotRunning", "(хост не запущено)",
            "infoTitle", "surecut-deck: відомості про сервер",
            "pairCodeLabel", "Код підключення",
            "copyCode", "Копіювати код",
            "addressHint", "Відкрийте одну з цих адрес на планшеті (подвійний клік копіює)",
            "colAddress", "Адреса",
            "colInterface", "Мережевий інтерфейс",
            "settingsTitle", "surecut-deck: параметри",
            "port", "Порт",
            "portHint", "Зміна перезапустить хост і змінить адресу на планшеті.",
            "startWithWindows", "Запускати разом із Windows",
            "startMinimized", "Не відкривати вікно під час запуску (лише в області сповіщень)",
            "regenCode", "Створити новий код підключення",
            "regenHint", "Підключені планшети буде відключено, знадобиться новий код.",
            "addFirewall", "Додати правило брандмауера (потрібні права адміністратора)",
            "save", "Зберегти",
            "cancel", "Скасувати",
            "firewallAdded", "Правило брандмауера додано (порт ",
            "firewallAddedTail", ", профіль «Приватний»).",
            "firewallFailed", "Не вдалося додати правило. Чи було надано підтвердження адміністратора?",
            "firewallError", "Не вдалося додати правило: ",
            "logTitle", "surecut-deck: журнал",
            "dropHere", "Перетягніть ярлик з робочого стола в будь-яке місце цього вікна: ціль і значок визначаються автоматично",
            "dropNow", "Відпустіть",
            "uiFailed", "Не вдалося завантажити інтерфейс:\\r\\n",
            "uiFailedHint", "\\r\\n\\r\\nМожливо, не встановлено середовище виконання WebView2.\\r\\nМожна продовжити через «Відкрити інтерфейс у браузері» в меню області сповіщень.",
            "buttonsAdded", " кнопок додано"
        });

        Add("ur", new string[] {
            "alreadyRunning", "surecut-deck پہلے سے چل رہا ہے۔",
            "running", "● چل رہا ہے  ·  پورٹ ",
            "stopped", "○ رکا ہوا",
            "pairCode", "جوڑنے کا کوڈ:  ",
            "openEditor", "ایڈیٹر کھولیں",
            "dragDrop", "شارٹ کٹ گھسیٹ کر چھوڑیں…",
            "serverInfo", "سرور کی تفصیل…",
            "openInBrowser", "انٹرفیس براؤزر میں کھولیں",
            "copyAddress", "کنکشن کا پتہ نقل کریں",
            "settings", "ترتیبات…",
            "log", "لاگ…",
            "restart", "دوبارہ شروع کریں",
            "stop", "روکیں",
            "start", "شروع کریں",
            "quit", "خارج ہوں",
            "nodeFailed", "Node.js شروع نہیں ہو سکا:\n\n",
            "nodeFailedHint", "\n\nNode.js نصب اور PATH میں ہونا چاہیے۔",
            "trayRunning", "surecut-deck: چل رہا ہے (پورٹ ",
            "trayStopped", "surecut-deck: رکا ہوا",
            "notGenerated", "(ابھی بنا نہیں)",
            "editorFellBack", "ایڈیٹر ونڈو نہیں کھل سکی، اس کے بجائے براؤزر استعمال ہو رہا ہے۔ تفصیل: لاگ",
            "copied", "نقل ہو گیا: ",
            "newCode", "نیا جوڑنے کا کوڈ: ",
            "newCodeHint", "\n\nٹیبلٹ کا کنکشن منقطع ہو جائے گا اور اسے نیا کوڈ درکار ہوگا۔",
            "autoStartFailed", "خودکار آغاز مرتب نہیں ہو سکا: ",
            "dropTitle", "surecut-deck: گھسیٹ کر چھوڑیں",
            "dropZone", "ڈیسک ٹاپ سے شارٹ کٹ گھسیٹیں\r\nاور یہاں چھوڑیں\r\n\r\n(پروگرام، فولڈر یا فائل بھی چلے گی)",
            "alwaysOnTop", "ہمیشہ سب سے اوپر",
            "whichPage", "کس صفحے میں شامل کریں",
            "refresh", "تازہ کریں",
            "added", "شامل شدہ",
            "close", "بند کریں",
            "iconYes", "  (آئیکن ✓)",
            "iconNo", "  (آئیکن نہیں)",
            "hostNotRunning", "(میزبان نہیں چل رہا)",
            "infoTitle", "surecut-deck: سرور کی تفصیل",
            "pairCodeLabel", "جوڑنے کا کوڈ",
            "copyCode", "کوڈ نقل کریں",
            "addressHint", "ٹیبلٹ پر ان میں سے ایک کھولیں (نقل کے لیے ڈبل کلک)",
            "colAddress", "پتہ",
            "colInterface", "نیٹ ورک انٹرفیس",
            "settingsTitle", "surecut-deck: ترتیبات",
            "port", "پورٹ",
            "portHint", "اسے بدلنے پر میزبان دوبارہ شروع ہوتا ہے اور ٹیبلٹ کا پتہ بدل جاتا ہے۔",
            "startWithWindows", "Windows کے ساتھ شروع کریں",
            "startMinimized", "آغاز پر ونڈو نہ کھولیں (صرف ٹرے)",
            "regenCode", "جوڑنے کا کوڈ نیا بنائیں",
            "regenHint", "جڑے ہوئے ٹیبلٹ منقطع ہو جائیں گے اور انہیں نیا کوڈ درکار ہوگا۔",
            "addFirewall", "فائر وال قاعدہ شامل کریں (ایڈمن درکار)",
            "save", "محفوظ کریں",
            "cancel", "منسوخ کریں",
            "firewallAdded", "فائر وال قاعدہ شامل ہو گیا (پورٹ ",
            "firewallAddedTail", "، نجی پروفائل)۔",
            "firewallFailed", "قاعدہ شامل نہیں ہو سکا۔ کیا ایڈمن کی منظوری دی گئی تھی؟",
            "firewallError", "قاعدہ شامل نہیں ہو سکا: ",
            "logTitle", "surecut-deck: لاگ",
            "dropHere", "ڈیسک ٹاپ سے شارٹ کٹ اس ونڈو میں کہیں بھی چھوڑیں: اس کا ہدف اور آئیکن خود بخود لے لیا جاتا ہے",
            "dropNow", "چھوڑ دیں",
            "uiFailed", "انٹرفیس لوڈ نہیں ہو سکا:\r\n",
            "uiFailedHint", "\r\n\r\nممکن ہے WebView2 رن ٹائم نصب نہ ہو۔\r\nآپ ٹرے مینو سے «انٹرفیس براؤزر میں کھولیں» کے ذریعے جاری رکھ سکتے ہیں۔",
            "buttonsAdded", " بٹن شامل ہوئے"
        });

        Add("vi", new string[] {
            "alreadyRunning", "surecut-deck đang chạy rồi.",
            "running", "● Đang chạy  ·  cổng ",
            "stopped", "○ Đã dừng",
            "pairCode", "Mã ghép nối:  ",
            "openEditor", "Mở trình chỉnh sửa",
            "dragDrop", "Kéo và thả lối tắt…",
            "serverInfo", "Chi tiết máy chủ…",
            "openInBrowser", "Mở giao diện trong trình duyệt",
            "copyAddress", "Sao chép địa chỉ kết nối",
            "settings", "Cài đặt…",
            "log", "Nhật ký…",
            "restart", "Khởi động lại",
            "stop", "Dừng",
            "start", "Bắt đầu",
            "quit", "Thoát",
            "nodeFailed", "Không thể khởi động Node.js:\n\n",
            "nodeFailedHint", "\n\nNode.js phải được cài đặt và có trong PATH.",
            "trayRunning", "surecut-deck: đang chạy (cổng ",
            "trayStopped", "surecut-deck: đã dừng",
            "notGenerated", "(chưa tạo)",
            "editorFellBack", "Không mở được cửa sổ chỉnh sửa, đang dùng trình duyệt thay thế. Chi tiết: Nhật ký",
            "copied", "Đã sao chép: ",
            "newCode", "Mã ghép nối mới: ",
            "newCodeHint", "\n\nMáy tính bảng sẽ bị ngắt kết nối và cần nhập mã mới.",
            "autoStartFailed", "Không thiết lập được tự động khởi động: ",
            "dropTitle", "surecut-deck: Kéo và thả",
            "dropZone", "Kéo lối tắt từ màn hình nền\r\nvà thả vào đây\r\n\r\n(chương trình, thư mục hoặc tệp cũng được)",
            "alwaysOnTop", "Luôn ở trên cùng",
            "whichPage", "Thêm vào trang nào",
            "refresh", "Làm mới",
            "added", "Đã thêm",
            "close", "Đóng",
            "iconYes", "  (biểu tượng ✓)",
            "iconNo", "  (không có biểu tượng)",
            "hostNotRunning", "(máy chủ không chạy)",
            "infoTitle", "surecut-deck: Chi tiết máy chủ",
            "pairCodeLabel", "Mã ghép nối",
            "copyCode", "Sao chép mã",
            "addressHint", "Mở một trong các địa chỉ này trên máy tính bảng (nhấp đúp để sao chép)",
            "colAddress", "Địa chỉ",
            "colInterface", "Giao tiếp mạng",
            "settingsTitle", "surecut-deck: Cài đặt",
            "port", "Cổng",
            "portHint", "Thay đổi giá trị này sẽ khởi động lại máy chủ và đổi địa chỉ trên máy tính bảng.",
            "startWithWindows", "Khởi động cùng Windows",
            "startMinimized", "Không mở cửa sổ khi khởi động (chỉ ở khay hệ thống)",
            "regenCode", "Tạo lại mã ghép nối",
            "regenHint", "Các máy tính bảng đang kết nối sẽ bị ngắt và cần nhập mã mới.",
            "addFirewall", "Thêm quy tắc tường lửa (cần quyền quản trị)",
            "save", "Lưu",
            "cancel", "Hủy",
            "firewallAdded", "Đã thêm quy tắc tường lửa (cổng ",
            "firewallAddedTail", ", hồ sơ Riêng tư).",
            "firewallFailed", "Không thêm được quy tắc. Bạn đã chấp thuận quyền quản trị chưa?",
            "firewallError", "Không thêm được quy tắc: ",
            "logTitle", "surecut-deck: Nhật ký",
            "dropHere", "Thả lối tắt từ màn hình nền vào bất kỳ chỗ nào trong cửa sổ này: đích và biểu tượng được lấy tự động",
            "dropNow", "Thả vào đây",
            "uiFailed", "Không tải được giao diện:\r\n",
            "uiFailedHint", "\r\n\r\nCó thể runtime WebView2 chưa được cài đặt.\r\nBạn có thể tiếp tục bằng \"Mở giao diện trong trình duyệt\" trong menu khay hệ thống.",
            "buttonsAdded", " nút đã được thêm"
        });

        Add("zh", new string[] {
            "alreadyRunning", "surecut-deck 已在运行。",
            "running", "● 正在运行  ·  端口 ",
            "stopped", "○ 已停止",
            "pairCode", "配对码：  ",
            "openEditor", "打开编辑器",
            "dragDrop", "拖放快捷方式…",
            "serverInfo", "服务器信息…",
            "openInBrowser", "在浏览器中打开界面",
            "copyAddress", "复制连接地址",
            "settings", "设置…",
            "log", "日志…",
            "restart", "重新启动",
            "stop", "停止",
            "start", "启动",
            "quit", "退出",
            "nodeFailed", "无法启动 Node.js：\n\n",
            "nodeFailedHint", "\n\nNode.js 必须已安装并位于 PATH 中。",
            "trayRunning", "surecut-deck：正在运行（端口 ",
            "trayStopped", "surecut-deck：已停止",
            "notGenerated", "（尚未生成）",
            "editorFellBack", "编辑器窗口无法打开，改用浏览器。详细信息：日志",
            "copied", "已复制： ",
            "newCode", "新的配对码： ",
            "newCodeHint", "\n\n平板电脑的连接会断开，需要输入新的配对码。",
            "autoStartFailed", "无法设置自动启动： ",
            "dropTitle", "surecut-deck：拖放",
            "dropZone", "将桌面上的快捷方式\r\n拖放到这里\r\n\r\n（程序、文件夹或文件也可以）",
            "alwaysOnTop", "始终置顶",
            "whichPage", "添加到哪个页面",
            "refresh", "刷新",
            "added", "已添加",
            "close", "关闭",
            "iconYes", "  （图标 ✓）",
            "iconNo", "  （无图标）",
            "hostNotRunning", "（主机未运行）",
            "infoTitle", "surecut-deck：服务器信息",
            "pairCodeLabel", "配对码",
            "copyCode", "复制配对码",
            "addressHint", "在平板电脑上打开其中一个地址（双击可复制）",
            "colAddress", "地址",
            "colInterface", "网络接口",
            "settingsTitle", "surecut-deck：设置",
            "port", "端口",
            "portHint", "更改后主机会重新启动，平板电脑上的地址也会改变。",
            "startWithWindows", "开机时启动",
            "startMinimized", "启动时不打开窗口（仅显示在通知区域）",
            "regenCode", "重新生成配对码",
            "regenHint", "已连接的平板电脑会断开，需要输入新的配对码。",
            "addFirewall", "添加防火墙规则（需要管理员权限）",
            "save", "保存",
            "cancel", "取消",
            "firewallAdded", "已添加防火墙规则（端口 ",
            "firewallAddedTail", "，专用配置文件）。",
            "firewallFailed", "无法添加规则。是否已通过管理员批准？",
            "firewallError", "无法添加规则： ",
            "logTitle", "surecut-deck：日志",
            "dropHere", "将桌面上的快捷方式拖放到本窗口的任意位置：会自动获取它的目标和图标",
            "dropNow", "放到这里",
            "uiFailed", "界面加载失败：\r\n",
            "uiFailedHint", "\r\n\r\n可能未安装 WebView2 运行时。\r\n可以用通知区域菜单中的“在浏览器中打开界面”继续。",
            "buttonsAdded", " 个按钮已添加"
        });
    }
}
